### PR TITLE
Valid business is better business

### PR DESCRIPTION
**Pull request by sparkiegeek**

### CODE REVIEW

**Review by Lukewh — CHANGES_REQUESTED** [review]
4 space indent on css? Having a giggle?

**Comment by sparkiegeek** [comment]
Any better now?

**Review by tbille — APPROVED** [review]
The business is approved!

**Review by Lukewh — APPROVED** [review]

**Comment by tbille** [comment]
@sparkiegeek thank you for your contribution, you are helping the community

**Pull request merged**
